name: 'SoleTrack - Shoe Inventory Management'
key: 'ST'
customer: 'Metro Kicks'
created: '2026-01-10'
phase: 'building'
tier: 'professional'
stack:
  language: 'typescript'
  framework: 'next'
  database: 'postgresql'
  deployment: 'railway'
